"""Initial

Revision ID: 4bc3c1593df7
Revises: 
Create Date: 2020-11-29 17:01:37.594486

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4bc3c1593df7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filmsSchedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('film_id', sa.String(length=36), nullable=False),
    sa.Column('schedule_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('filmsschedules')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filmsschedules',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('film_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('schedule_id', mysql.VARCHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], name='filmsschedules_ibfk_1'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name='filmsschedules_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('filmsSchedules')
    # ### end Alembic commands ###
